### ISSUE TITLE
Docker build for micro service 2 failing

### ISSUE THREAD

**Issue by eldhomathulla** [hiteshkumardasika/airavata-assignment1#1]
Docker build for microsrvice 2 was failing

**Comment by hiteshkumardasika** [comment]
This isnt the repository i worked on. Sorry for giving the wrong link. Didnt have access to airavata-courses during the time of submission. Hence i uploaded the assignment to my own github. 
Check this
https://github.com/airavata-courses/hiteshkumardasika
